
name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: 
      - completed

jobs:

  EC2-Deploy:

    runs-on: self-hosted

    steps: 
    - name: Pull Docker image
      run: sudo docker pull xgera/entorno-hormiguero:latest
    - name: Delete Old Docker Container
      run: sudo docker rm -f entorno-hormiguero || true
    - name: Run Docker Container
      run: sudo docker run -e MONGODB_URI="echo $MONGODB_URI" -d -p 8080:8080 --name entorno-hormiguero xgera/entorno-hormiguero:latest
